### ISSUE TITLE
询问问题

### ISSUE THREAD

**Issue by Esword618** [FeiGeChuanShu/CodeFormer-ncnn#1]
./ncnn_codeformer ./02.png 0
询问一下，ncnn_codeformer 这个我怎么找不到，第一次搞ncnn，不太明白

**Comment by FeiGeChuanShu** [comment]
> ./ncnn_codeformer ./02.png 0 询问一下，ncnn_codeformer 这个我怎么找不到，第一次搞ncnn，不太明白

mkdir build
cd build
cmake ..
make -j$(nproc)

**Comment by Esword618** [comment]
好的，谢谢

**Comment by madtunebk** [comment]
/usr/bin/ld: /home/nobus/firemypc/CodeFormer-ncnn/ncnn/lib/libncnn.a(glu.cpp.o):glu.cpp:(.text+0x437): more undefined references to `__expf_finite' follow
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ncnn_codeformer.dir/build.make:247: ncnn_codeformer] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/ncnn_codeformer.dir/all] Error 2
make: *** [Makefile:91: all] Error 2


How do we fix this ?

**Comment by madtunebk** [comment]
Compile last verion of ncnn and copy paste in to /home/<<username>>/firemypc/CodeFormer-ncnn/ncnn

**Comment by xalteropsx** [comment]
@FeiGeChuanShu their is no makefile how can u make it ?

make: *** No targets specified and no makefile found.  Stop.
